export const requestURL = "http://localhost:3002";

export const gameOptions = [
    { value: "valorant", label: "Valorant" },
    { value: "rocket-league", label: "Rocket League" },
];
export const platformOptions = [{ value: "medal", label: "Medal" }];

export const valRankOptions = [
    { value: "iron1", label: "Iron 1" },
    { value: "iron2", label: "Iron 2" },
    { value: "iron3", label: "Iron 3" },
    { value: "bronze1", label: "Bronze 1" },
    { value: "bronze2", label: "Bronze 2" },
    { value: "bronze3", label: "Bronze 3" },
    { value: "silver1", label: "Silver 1" },
    { value: "silver2", label: "Silver 2" },
    { value: "silver3", label: "Silver 3" },
    { value: "gold1", label: "Gold 1" },
    { value: "gold2", label: "Gold 2" },
    { value: "gold3", label: "Gold 3" },
    { value: "plat1", label: "Platinum 1" },
    { value: "plat2", label: "Platinum 2" },
    { value: "plat3", label: "Platinum 3" },
    { value: "diamond1", label: "Diamond 1" },
    { value: "diamond2", label: "Diamond 2" },
    { value: "diamond3", label: "Diamond 3" },
    { value: "ascendant1", label: "Ascendant 1" },
    { value: "ascendant2", label: "Ascendant 2" },
    { value: "ascendant3", label: "Ascendant 3" },
    { value: "immortal1", label: "Immortal 1" },
    { value: "immortal2", label: "Immortal 2" },
    { value: "immortal3", label: "Immortal 3" },
    { value: "radiant", label: "Radiant" },
];

export const rlRankOptions = [
    { value: "bronze1", label: "Bronze 1" },
    { value: "bronze2", label: "Bronze 2" },
    { value: "bronze3", label: "Bronze 3" },
    { value: "silver1", label: "Silver 1" },
    { value: "silver2", label: "Silver 2" },
    { value: "silver3", label: "Silver 3" },
    { value: "gold1", label: "Gold 1" },
    { value: "gold2", label: "Gold 2" },
    { value: "gold3", label: "Gold 3" },
    { value: "plat1", label: "Platinum 1" },
    { value: "plat2", label: "Platinum 2" },
    { value: "plat3", label: "Platinum 3" },
    { value: "diamond1", label: "Diamond 1" },
    { value: "diamond2", label: "Diamond 2" },
    { value: "diamond3", label: "Diamond 3" },
    { value: "champ1", label: "Champion 1" },
    { value: "champ2", label: "Champion 2" },
    { value: "champ3", label: "Champion 3" },
    { value: "grandchamp1", label: "Grand Champion 1" },
    { value: "grandchamp2", label: "Grand Champion 2" },
    { value: "grandchamp3", label: "Grand Champion 3" },
    { value: "supersoniclegend", label: "Supersonic Legend" },
];